apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: gcr.io/google-containers/elasticsearch:v6.2.5
        name: elasticsearch
        ports:
        - containerPort: 80
